Add confirmations when removing an entire node before setting disks to 0 weight
sapcc/swift-ring-artisan pull request #99
Opened 2023-09-04 14:20 UTC by SuperSandro2000

2023-09-05 13:49 UTC, majewsky requested changes
Since this PR is mostly refactorings and one new feature, my review is mostly stylistic nitpicks and one actual issue.

2023-09-21 13:39 UTC, SuperSandro2000 commented on pkg/rules/rules.go
> +	for _, zone := range zones {
This is later used in line 189 and I didn't want to collect the infos twice.

2023-09-21 13:55 UTC, majewsky approved these changes

2023-09-21 13:56 UTC, majewsky requested changes
Sorry for the noise, I only reviewed the force-push diff and did not see that there were some unaddressed concerns.

2023-09-21 14:02 UTC, SuperSandro2000 commented
forgot to push that 😅

2023-09-25 09:06 UTC, majewsky approved these changes

2023-09-25 09:06 UTC, merged